spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/api/inventory/**
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/customers/**
